### ISSUE TITLE
Download schlägt fehl

### ISSUE THREAD

**Issue by Sedrah87** [iNaD/download-station-ndrmediathek#2]
Hi,

danke für deine Bemühungen und die coole Möglichkeit an die Videos heran zu kommen. Aktuell scheitert leider der Download von folgendem Video aus der Mediathek http://www.ndr.de/fernsehen/Der-Abenteuerfotograf,abenteuerfotograf112.html
Wäre super wenn ich das Video herunterladen kann.

Danke

**Comment by iNaD** [comment]
Hi Sedrah87,

entschuldige die späte Antwort. Meine Arbeit nimmt aktuell wieder ziemlich viel Zeit in Anspruch. Ich kann dir also nicht genau sagen, wann ich wieder Zeit finde.

**Comment by iNaD** [comment]
Duplicate of #1
